- Dockerfile
- README.md
- src/common/util/secrets.ts
- src/graphql.ts
- src/pubsub.ts
> PORT + BIND_ADDRESS

- src/model/index.ts
- src/model/transaction.ts
- src/model/transaction_memo.ts
- src/schema/type_defs.ts
- tests/factories/transaction.ts
- tests/model/transaction.test.ts
> Add memo, time bounds, fee and source accounts to transactions

- src/database.ts
- src/dgraph_import.ts
- src/ingest/cursor.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/asset.ts
- src/schema/resolvers/data_entry.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/signer.ts
- src/schema/resolvers/transaction.ts
- src/schema/resolvers/trust_line.ts
- src/util/stellar.ts
- tests/unit/ingest/cursor.test.ts
Resolve #82 
Well, default export in `database` module was a culprit here. I don't know exactly, how it works, but it works 😁
> Fix modules import in `dgraph_import.ts`

- src/database.ts
- src/graphql.ts
- src/model/asset_input.ts
- src/model/index.ts
- src/model/offer.ts
- src/repo/offers.ts
- src/schema/resolvers/index.ts
- src/schema/resolvers/offer.ts
- src/schema/resolvers/util.ts
- src/schema/type_defs.ts
- src/util/asset.ts
- src/util/memo.ts
> Orders query

- src/storage/builders/account.ts
- src/storage/builders/asset.ts
- src/storage/builders/ledger.ts
- src/storage/builders/operation.ts
- src/storage/builders/operations/account_merge_op.ts
- src/storage/builders/path_payment_result.ts
- src/storage/builders/transaction.ts
- src/storage/builders/trust_line_entry.ts
- src/storage/queries/account_transactions.ts
- src/storage/queries/operations.ts
For filtering with has(), better distribution.
> Unique key predicate for every entity

- src/model/factories/transaction_factory.ts
- src/model/factories/transaction_with_xdr_factory.ts
- src/model/transaction.ts
- src/storage/builders/transaction.ts
- src/storage/types.ts
- tests/unit/model/transaction_with_xdr.test.ts
This fix became larger than I expected, so I need another couple of eyes on it 👀
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/118)
> Ingest tx time bounds, as Date

- src/datasource/horizon.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/transaction.ts
- src/schema/resolvers/util.ts
- src/schema/type_defs.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/133)
> Ledger transactions connection

- src/datasource/horizon.ts
- src/schema/index.ts
- src/schema/ledgers.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/util.ts
- src/schema/type_defs.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/135)
> Ledger operations connection

- src/changes_extractor.ts
- src/ingest/subscription_payload_collection.ts
- src/ingestd.ts
- src/model/factories/asset_factory.ts
- src/model/factories/offer_factory.ts
- src/model/offer_subscription_payload.ts
- src/pubsub.ts
- src/repo/offers.ts
- src/schema/offers.ts
- src/schema/resolvers/offer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/134)
> Rough sketch of the best bid/ask subscriptions

- src/datasource/horizon.ts
- src/datasource/types.ts
- src/model/asset_input.ts
- src/schema/assets.ts
- src/schema/index.ts
- src/schema/resolvers/asset.ts
- src/schema/type_defs.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/139)
> Serve assets from Horizon

- src/datasource/horizon.ts
- src/datasource/types.ts
- src/model/factories/asset_factory.ts
- src/schema/index.ts
- src/schema/payment_path.ts
- src/schema/resolvers/index.ts
- src/schema/resolvers/payment_path.ts
- src/schema/resolvers/util.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/143)
> findPaymentPaths

- src/datasource/horizon.ts
- src/datasource/types.ts
- src/graphql_server.ts
- src/model/factories/asset_factory.ts
- src/schema/index.ts
- src/schema/resolvers/index.ts
- src/schema/resolvers/trade_aggregations.ts
- src/schema/resolvers/util.ts
- src/schema/trade_aggregations.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/144)
> Trade aggregations query

- src/datasource/horizon.ts
- src/schema/accounts.ts
- src/schema/operations.ts
- src/schema/resolvers/operation.ts
- src/schema/resolvers/util.ts
Standalone query for _all_ operations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/142)
> All operations query

- src/datasource/horizon.ts
- src/schema/operations.ts
- src/schema/resolvers/operation.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/147)
> Single operation query

- src/datasource/horizon.ts
- src/datasource/types.ts
- src/repo/offers.ts
- src/schema/accounts.ts
- src/schema/ledgers.ts
- src/schema/operations.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/operation.ts
- src/schema/resolvers/trades.ts
- src/schema/resolvers/transaction.ts
- src/schema/resolvers/util.ts
- src/schema/trades.ts
- src/schema/transactions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/148)
> Payments queries

- src/datasource/horizon.ts
- src/datasource/types.ts
- src/model/effect.ts
- src/model/factories/asset_factory.ts
- src/model/factories/effect_factory.ts
- src/model/factories/index.ts
- src/model/index.ts
- src/schema/accounts.ts
- src/schema/effects.ts
- src/schema/index.ts
- src/schema/ledgers.ts
- src/schema/operations.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/effect.ts
- src/schema/resolvers/index.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/transaction.ts
- src/schema/resolvers/util.ts
- src/schema/transactions.ts
- src/schema/type_defs.ts
Really huge PR about mirroring effects queries from Horizon API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/145)
> Effects queries

- src/schema/accounts.ts
- src/schema/assets.ts
- src/schema/effects.ts
- src/schema/ledgers.ts
- src/schema/offers.ts
- src/schema/operations.ts
- src/schema/order_book.ts
- src/schema/payment_path.ts
- src/schema/resolvers/data_entry.ts
- src/schema/trade_aggregations.ts
- src/schema/trades.ts
- src/schema/transactions.ts
- src/schema/type_defs.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/150)
> GraphQL schema documentation

- src/model/account.ts
- src/repo/accounts.ts
- src/schema/accounts.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/util.ts
Adresses #161 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/162)
> Filter accounts by home domain

- package.json
- src/graphql_server.ts
- src/ingest/worker.ts
- src/ingestd.ts
- src/init.ts
- src/model/account.ts
- src/model/balance.ts
- src/model/balance_values.ts
- src/model/factories/account_factory.ts
- src/model/factories/balance_factory.ts
- src/model/factories/balance_values_factory.ts
- src/model/factories/offer_factory.ts
- src/model/ledger.ts
- src/pubsub.ts
- src/repo/ledger_headers.ts
- src/schema/accounts.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/balance.ts
- src/schema/resolvers/ledger.ts
- src/schema/resolvers/offer.ts
- src/schema/type_defs.ts
- src/util/base_reserve.ts
- src/util/stellar.ts
- tests/factories/account.ts
- tests/unit/model/balance.test.ts
- yarn.lock
Here's the implementation of new fields in the schema for `Account` balances, `spendableBalance` and `receivableBalance`. Calculation of these fields takes buying and selling liabilities into consideration, and for native balance also minimum balance is considered too. Also, the user will be able to query minimum balance for the single account
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/160)
> Spendable and receivable balances

- _experimental/model/transaction.ts
- package.json
- src/changes_extractor.ts
- src/datasource/types.ts
- src/model/balance_subscription_payload.ts
- src/model/balance_values.ts
- src/model/factories/asset_factory.ts
- src/model/factories/balance_values_factory.ts
- src/model/factories/operation_data_mapper/horizon.ts
- src/model/factories/transaction_with_xdr_factory.ts
- src/model/native_balance_subscription_payload.ts
- src/model/offer_subscription_payload.ts
- src/model/offer_values.ts
- src/model/operation.ts
- src/model/trade.ts
- src/model/transaction.ts
- src/schema/operations.ts
- src/schema/resolvers/operation.ts
- src/schema/resolvers/transaction.ts
- src/util/asset.ts
- src/util/memo.ts
- src/util/xdr_refiner.ts
- tests/integration/integration.test.ts
- tests/unit/memo.test.ts
- tsconfig.json
- yarn.lock
According to new stellar core version, we now have `ManageSellOffer`, `ManageBuyOffer` and `CreatePassiveSellOffer` operations. This PR reflects these changes. Also `stellar-base` dependency is updated
Resolves #165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/166)
> Update to catch up with stellar core v11

- src/init.ts
- src/model/factories/asset_factory.ts
- src/model/factories/signer_factory.ts
- src/model/signer.ts
- src/schema/accounts.ts
- tests/factories/account.ts
- tests/unit/model/balance.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/172)
> Add signer type to the schema

- .travis.yml
- package.json
- src/datasource/types.ts
- src/model/factories/operation_data_mapper/horizon.ts
- src/model/operation.ts
- src/schema/operations.ts
- src/schema/resolvers/operation.ts
- src/util/xdr_refiner.ts
- yarn.lock
Upcoming version of stellar core will introduce new operation type: `PathPaymentStrictSend`. So we should be ready 🙂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/183)
> Preparing for stellar core v12

- package.json
- src/init/graphql_server.ts
- src/init/ingestd.ts
- src/init/stellar.ts
- src/model/factories/transaction_with_xdr_factory.ts
- src/repo/transactions.ts
- src/schema/resolvers/account.ts
- src/schema/resolvers/ledger.ts
- src/storage/base.ts
- src/storage/connection.ts
- src/storage/connection_pool.ts
- src/util/logger.ts
- tests/integration/integration.test.ts
- tests/unit/ingest/cursor.test.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/193)
> Protocol 13 support

- src/pubsub.ts
- src/schema/resolvers/transaction.ts
- src/schema/transactions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/197)
> Transactions subscription

- src/schema/resolvers/transaction.ts
- src/schema/transactions.ts
- src/storage/base.ts
- src/util/secrets.ts
Resolves #42 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/astroband/astrograph/192)
> Submit transaction mutation
